#! /usr/bin/env ruby -w

require 'bundler/setup'

require 'nokogiri'
require 'open-uri'

arg = ARGV[0] || 'Rails5'

doc = Nokogiri::HTML(open("http://www.google.com/search?q=#{arg}"))

doc.css('h3.r a').each do |link|
  puts link.content
end
